version: '3'
services:
  aiwechat:
    container_name: aiwechat
    build:
      # 构建上下文根目录
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - "./log:/project/log"
    ports:
      - "9899:9898"
    environment:
      - TZ=Asia/Shanghai
    network_mode: "bridge"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "ps aux | grep -v grep | grep start.sh || exit 1" ]
      interval: 30s
      timeout: 5s
      retries: 3
